server:
  port: 8081

spring:
  main:
    banner-mode: off
  cache:
    caffeine:
      spec: maximumSize=48,expireAfterAccess=600s

logging:
  level:
    com.example.currencyrateservice.dataclient: debug

cb:
  currencyrate:
    url: https://www.cbr.ru/scripts/XML_daily.asp
